### ISSUE TITLE
Component dlls not found.

### ISSUE THREAD

**Issue by manishkungwani** [bitrise-steplib/steps-xamarin-components-restore#5]
We have multiple components in our Xamarin.Android project, and the Component restore step passes. But during the archive step, the assemblies are not found.

Can you please help.

**Comment by viktorbenei** [comment]
Hi @manishkungwani, 

We'll need a bit more info, can you please send the failing build's Bitrise.io url to us through the onsite chat or email?

**Comment by manishkungwani** [comment]
@viktorbenei sent via on-site chat and here is the url as well - https://www.bitrise.io/build/02254ffa3c30fbaf
